### ISSUE TITLE
Translations from crowdin

### ISSUE THREAD

**Issue by JoseGalRe** [qklabs/qksms#100]
hi, thanks for the app!; now is open source you can create a free account in crowdin for we translate the app to all languages

thanks! for all!

**Comment by moezbhatti** [comment]
Oh, great idea! I forgot about that.

**Comment by moezbhatti** [comment]
I've contacted Crowdin, I'm in the process of getting this set up

**Comment by JoseGalRe** [comment]
Thanks! this would help us all!
