### ISSUE TITLE
Title bar bug

### ISSUE THREAD

**Issue by Samcfuchs** [qklabs/qksms#103]
### DESCRIPTION
The title bar which reads "conversations" changes to the name of the most recent conversation after reopening the app.

### STEPS
1. Open app in conversations view.
2. Open a conversation
3. Click the back button to return to the conversations view.
4. Click home to close the app.
5. Reopen the app by tapping on its icon, which will return ou to the conversations view.

### EXPECTED
The title bar continues to say conversations.

### OBSERVATIONS
The title bar is replaced with the name of the conversation you opened.

I have screenshots if necessary.

**Comment by moezbhatti** [comment]
Nice, the repro steps work for me

**Comment by ahattat** [comment]
Works for me too

**Comment by moezbhatti** [comment]
Fixed in #145
