### ISSUE TITLE
Avatars in conversation list don't refresh when display option is changed

### ISSUE THREAD

**Issue by zax9** [qklabs/qksms#106]
When changing the value of the setting "Appearance->Hide conversation avatars" and returning to the conversation list, the conversations immediately visible on-screen will not reflect the new value of the setting. Only after scrolling the currently-displayed conversations off-screen and then scrolling back will the avatar display setting in the conversation list be properly reflected.

**Comment by moezbhatti** [comment]
Confirmed, thanks for the report

**Comment by Samcfuchs** [comment]
I think this is just that appearance settings don't change until you refresh the elements, which is most easily done by restarting the app.

**Comment by zax9** [comment]
It's most easily done by scrolling the list of conversations so that those that aren't showing the count onscreen go offscreen, then the newly-onscreen conversations display correctly. Scrolling back to the original group, they are then refreshed. You don't need to exit the app.

I think that when exiting the options screen, it should just force a UI element refresh.

**Comment by Samcfuchs** [comment]
Yep, I'm with @zax9 . Exiting options should force a refresh.

**Comment by moezbhatti** [comment]
No worries, I already have a really good way to fix this
