### ISSUE TITLE
Many of the Settings text are cut off 

### ISSUE THREAD

**Issue by Ravenstencil** [qklabs/qksms#11]
"Hide sent message ava".

**Comment by srcreigh** [comment]
Unfortunately we haven't been able to reproduce this issue.

@Ravenstencil can you attach android version and the device model?

**Comment by Ravenstencil** [comment]
ZTE Z995 with Android 4.1.2

**Comment by srcreigh** [comment]
Thanks. I'll try reproducing this issue on a 4.1.2 emulator now.

**Comment by srcreigh** [comment]
Can't reproduce on the 4.1.2 emulator.

**Comment by Samcfuchs** [comment]
Could not repro on Moto X 2013.
