### ISSUE TITLE
Widget title bar text

### ISSUE THREAD

**Issue by Samcfuchs** [qklabs/qksms#113]
In the title bar of the widget, when it is sized to 3x3, the s in "conversations" is bumped to the next line. It's not critical, but it looks horrendous. This may be related to screen size.

I can provide screenshot if necessary.

**Comment by moezbhatti** [comment]
A screenshot would be helpful!

**Comment by l3d00m** [comment]
I cannot confirm this, but to prevent this line 34 +35 in QKSMS\src\main\res\layout\widget.xml has to be added with
~~~
android:ellipsize="end"
android:lines="1"
~~~

This truncates the text instead of making a new line. (Not sure if this is better)

**Comment by moezbhatti** [comment]
Definitely an improvement, and probably the right fix. I just want to see how much is being cut off / acting weird. Doesn't happen on my phone

**Comment by Samcfuchs** [comment]
@moezbhatti I am going to link to imgur because github doesn't let you embed on mobile.

http://i.imgur.com/C2ykjWj.jpg

I hope I cropped out all the personal info.

**Comment by Samcfuchs** [comment]
BTW this is Moto X 2013.

**Comment by moezbhatti** [comment]
Fixed in https://github.com/qklabs/qksms/commit/b53dcb4cd8b9d57caef9a1eb4eb030c87a60a556
