### ISSUE TITLE
Status bar shows gradient on Samsung devices running Lollipop

### ISSUE THREAD

**Issue by moezbhatti** [qklabs/qksms#124]
Instead of showing the flat style for Lollipop, they show the Kitkat gradient which is super ugly. I've had a lot of reports about this, but I'm unable to test this as I have a Nexus 5.

Screenshot:

![screenshot_2015-08-16-08-11-03](https://cloud.githubusercontent.com/assets/4358785/9321949/e77caa6c-453a-11e5-995c-d5914025faa0.png)

**Comment by InfinityDeltaX** [comment]
On a Note 4 running Android 5.0.1, the "Tinted status bar" option seems to work as advertised, switching between gradient and flat status bars. Could you please further clarify the issue?

**Comment by moezbhatti** [comment]
The color works, but it shows a gradient instead of using the flat style found on lollipop. The screenshots in the README show it correctly

**Comment by pytt-** [comment]
Same thing happens on my Sony Xperia Z3 Compact. 

![screenshot](http://i.imgur.com/dhHP2gK.png)

**Comment by theLOLflashlight** [comment]
This bug exists on the Xperia ZL running Android 4.4, 5.0 and 5.1
