### ISSUE TITLE
Ability to block / whitelist / blacklist senders.

### ISSUE THREAD

**Issue by aqeeliz** [qklabs/qksms#127]
Add an ability to block incoming sms. It could be either whitelist (e.g. your contact list) or blacklist.

The way Google's Messenger do this, is each conversation has a 'People' button, and you can block that sender from there. You still recieve messages from them, but there is no notification and they are automatically archived (so you don't see them in your main SMS window).

**Comment by moezbhatti** [comment]
Implemented blacklist in #209

**Comment by moezbhatti** [comment]
We can open separate issues for the other features individually
