### ISSUE TITLE
Contact is removed when adding an attachment

### ISSUE THREAD

**Issue by Ravenstencil** [qklabs/qksms#14]
Selected a contact and after adding an attachment it changes the contact name to the phone number and when I attempt to send it I'm shown a message stating "Select some contacts to send this message to!".

**Comment by srcreigh** [comment]
Thanks @Ravenstencil. I can't repro this. I tried with these steps for both the popup compose and the in-app compose:

1. Open the compose screen
2. Select a contact
3. Attach an image

What you described did not happen. The name remained there. Can you provide more details?

**Comment by Ravenstencil** [comment]
Those are precisely the steps that I used.

It must be a hardware issue or an OS issue. I'm running Android 4.1.2.
