### ISSUE TITLE
Writting Issue

### ISSUE THREAD

**Issue by BTW30s** [qklabs/qksms#142]
android ICS
When I write it doesn't show suggestions when t9 is on and when I press space it makes the first letter big, like when you start a new sentence.

**Comment by borovac** [comment]
I have the same problem. Stock lollipop on N5. SwiftKey suggestions do not work at all. Outside of qksms, suggestions work fine.

**Comment by l3d00m** [comment]
I cannot reproduce this. SwiftKey suggestions works. No difference to other text input fields. LG G2 Stock 5.0.2

**Comment by borovac** [comment]
Hey, clearing data helped.
I was afraid that some setting caused it, but couldn't reproduce it either.

**Comment by borovac** [comment]
Hey, this started happening again. Luckily, I was able to recreate it.
Whenever I click enter key to send a message, instead of adding a new line, SwiftKey can't load predictions. This is very annoying, and I hope it gets fixed.

**Comment by l3d00m** [comment]
Can reproduce. Change enter button behavior to send message and swiftkey predictions won't work.
