### ISSUE TITLE
Hide sender too in Private Notifications

### ISSUE THREAD

**Issue by xavihernandez** [qklabs/qksms#148]
Hi,

It could be good to be able to hide sender too in Notification.
I think you can just rename Setting entry by something like "Hide content of message in notification" which will be responsible to hide the content, and create a new entry "Hide sender in notification". Then we will eb able to hide one of them or both as we want.

Well it's kinda easy to do but I have no time to edit code and pull a request ;p

**Comment by xavihernandez** [comment]
thanks @l3d00m

**Comment by l3d00m** [comment]
Can be closed @moezz
