### ISSUE TITLE
Need option to remove buttons from notification 

### ISSUE THREAD

**Issue by 1112e** [qklabs/qksms#150]
If I want to view the message, I click the notification, if i want to hide it I swipe away. I don't need mark read and reply buttons

**Comment by moezbhatti** [comment]
They perform different functions as opposed to just clicking on the notification. Reply allows you to view the QK Reply popup and Mark Read lets you dismiss it and mark it read so it doesn't bug you later

I don't think there are enough people who would want something like this to warrant adding yet another option in the settings
