### ISSUE TITLE
Automatic night mode not working

### ISSUE THREAD

**Issue by lanedarby** [qklabs/qksms#158]
Automatic night mode doesn't work. It was fixed in a previous update (I think 1.7 or something), but it appears to be broken again. It works each time I reset it (check and uncheck the box and reselect the times), but it kind of defeats the purpose of automatic night mode by doing that. I'm running 2.0.1

**Comment by Samcfuchs** [comment]
Night mode works fine on my Moto X 2013,  Android v5.1

**Comment by lanedarby** [comment]
It works when I change the background colour or I uncheck and recheck it, but as I said, it kinda defeats the purpose of 'automatic'. I'm running CM12.1 (5.1.1) on a Z3, so that could be it

**Comment by sentrysticks** [comment]
nexus 6, 5.1.1 stock no root, QK version 2.1.0

the Auto night mode works in the pm but doesn't change back in the am which IMO is the more important one
