### ISSUE TITLE
QK-Reply window should take more space by default

### ISSUE THREAD

**Issue by l3d00m** [qklabs/qksms#166]
### DESCRIPTION
The QK-Reply window is very small. I know I can expand it through the button, but it should show more lines by default
### STEPS
1. Get a SMS with ~100 or more characters
1. (Open it through notfication -> reply)
2. QK-Reply window only shows the last 3 lines although there's much more free space on screen

### EXPECTED
The windows should take more space in screen so I don't need to scroll for every second line.

### SCREENSHOTS
![screenshot_2015-08-21-10-24-46](https://cloud.githubusercontent.com/assets/12055376/9404317/e4e31406-47ee-11e5-9e88-4f55bef46510.png)
![screenshot_2015-08-21-10-25-25](https://cloud.githubusercontent.com/assets/12055376/9404334/0072c464-47ef-11e5-8dd8-7fe75c21972f.png)

**Comment by jjness** [comment]
I too have this problem, though mine often doesn't even show any of the text. For example, a single text reply reading "lol" wouldn't show anything but the borders of the quick reply window, that's how small it was. Samsung S4 Android v. 4.4.4

I hope this is proper protocol for reporting bugs! I've never used GitHub but after sending a message to one of the devs on his Reddit thread, I saw a link here and this looked more official.

**Comment by l3d00m** [comment]
You've found the right place to report bugs! It's easier for devs to track the issues here.
You can also view other issues here that needs to be [reproduced](https://github.com/qklabs/qksms/issues?q=is%3Aopen+is%3Aissue+label%3Aneeds-repro)

**Comment by moezbhatti** [comment]
Fixed in 60a07ec
