### ISSUE TITLE
Send Icon doesn't line up/fit

### ISSUE THREAD

**Issue by IAreKyleW00t** [qklabs/qksms#169]
**Device**: OnePlus One _(bacon)_
**OS**: CM-12.1-20150822-UNOFFICIAL-Sultan-bacon [[xda-link](http://forum.xda-developers.com/oneplus-one/orig-development/rom-kernel-unofficial-cyanogenmod-12-1-t3120259)]
**Android Version**: 5.1.1
**App Version**: 2.0.1

**Bug**: When typing a new message, the "+" turns into a ">" that doesn't fully line up at the point (see screenshot).

_[[full-size](https://cloud.githubusercontent.com/assets/1072572/9425977/a3e3f7f2-48f4-11e5-87e3-bc68ec160a8e.png)]_
![qksms_bug_small](https://cloud.githubusercontent.com/assets/1072572/9425976/8d789fe0-48f4-11e5-9424-6e7e2d963914.png)

_edit: greatly improved report (better wording/spelling)_

**Comment by moezbhatti** [comment]
This was fixed in #135, it'll be part of the next update

**Comment by IAreKyleW00t** [comment]
Ah, I tried looking through old issues to see if this was already addressed and I must have missed it.

Apologizes!

**Comment by moezbhatti** [comment]
No worries!
