### ISSUE TITLE
Remove roboto assets to cut down app size

### ISSUE THREAD

**Issue by moezbhatti** [qklabs/qksms#170]
http://stackoverflow.com/questions/19691530/valid-values-for-androidfontfamily-and-what-they-map-to
http://stackoverflow.com/questions/14343903/what-is-the-equivalent-of-androidfontfamily-sans-serif-light-in-java-code

This might cause some issues with the `medium` text since that one is only available after API 21

**Comment by eberkund** [comment]
Sounds like a good idea

**Comment by moezbhatti** [comment]
Did some investigating and tried implementing this, but it turns out that you can't always depend on Roboto to exist on the phone. I tried building the app with and without the fonts installed, and it adds less than 0.2MB, so it'll be better to just leave them in
