### ISSUE TITLE
Message tapping/holding not working

### ISSUE THREAD

**Issue by borovac** [qklabs/qksms#171]
I've noticed that in messages containing phone numbers (or any numbers that the app thinks are phone numbers) I  can't tap to get info, or hold for copying, forwarding etc.
In other messages it works fine.

Don't mind that the language on screenshots isn't English. :)
![screenshot_2015-08-17-00-12-55](https://cloud.githubusercontent.com/assets/12745167/9427835/adbf91cc-4990-11e5-9fc4-faad399af92b.png)
![screenshot_2015-08-23-10-14-33](https://cloud.githubusercontent.com/assets/12745167/9427834/adbe7440-4990-11e5-9def-bc98d0251ffa.png)

**Comment by C-Flat** [comment]
It does it with URLs too

**Comment by C-Flat** [comment]
It's because when you click or long click on a message you're not actually clicking the message, but the   LinearLayout that the message sits on. When there's a link or number in the message the message TextView becomes clickable and blocks you from clicking the ListView it's on. You are still able to click or long click the area beside the message to get the popup for now

**Comment by moezbhatti** [comment]
@C-Flat that's correct. I wonder if there's a way to make it pass other click events to its parent

**Comment by licaon-kter** [comment]
Any news on this? :(

**Comment by therob84** [comment]
I can confirm this bug. It happens for numbers and for links, including accidently charsettings like "Hello.How are you?" is interpreted as a link with "hello.how" and it provokes that the whole message is not clickable for long-tap!

I find it is a no-go, if I cannot choose messages with links inside....doesn't matter what the problem with programming is...

Any news with this?

I use v2.5.2 as standard app with Android 5.1@Fairphone2.

**Comment by C-Flat** [comment]
@therob84 I did find a work around. You can still click and long press the space to the left and right of the message to see detailed info.

**Comment by therob84** [comment]
@C-Flat: yep, you are right, I can confirm this behaviour. (Can we call it now as bug, or as feature?)

**Comment by KashifAnwaar** [comment]
@C-Flat @therob84 It's working in stock Messaging app but not in qksms, why don;t you guys check how?
