### ISSUE TITLE
Textra gives notification saying QKSMS interferes

### ISSUE THREAD

**Issue by mike-u** [qklabs/qksms#172]
![2015-07-22 20 24 11](https://cloud.githubusercontent.com/assets/8935879/9429759/3d619302-49aa-11e5-9883-3f8b80c96bda.png)

Is this a known issue? I'm not sure if this is even the right place to post it. This is with Textra set as default sms app, QK just installed and not even opened.

**Comment by moezbhatti** [comment]
I'm not sure if anything can be done from my end, this is Textra doing it as far as I know

**Comment by mike-u** [comment]
Alright, just wondered if you knew of it/if there was any legitimacy to this. I'll close the issue.
