### ISSUE TITLE
Latest Master: Receiving text toast always "sms desde numero #XXX.. "

### ISSUE THREAD

**Issue by JonShepChen** [qklabs/qksms#176]
Using the latest version of master branch, whenever I receive a message, the toast that appears always is the spanish "sms desde numero #xxx-xxx-xxxx" regardless of the language I set through phone settings (specifically tried English, French, Chinese). 

Testing on a Nexus 5.

Anyone able to reproduce this?

**Comment by l3d00m** [comment]
Cannot repro using the latest master branch. LG G2 5.0.2

**Comment by JonShepChen** [comment]
I'll look into it again tonight. Will close if I find out it's something on my side.

**Comment by moezbhatti** [comment]
Never seen this before, it might be unrelated to QKSMS

**Comment by JonShepChen** [comment]
Reinstalled the version currently on Google Play. I'm still getting this issue. Guess it's some configuration on my end outside of the app. Closing for now.
