### ISSUE TITLE
Date and time formatting does not reflect my locale settings.

### ISSUE THREAD

**Issue by AmyAmy** [qklabs/qksms#178]
Time is formatted an 4:08 PM instead of 16:08.

Even tho I'm in Europe and "Use 24-hour format" in Android Date & Time settings is on.
![screenshot_2015-08-24-16-53-14](https://cloud.githubusercontent.com/assets/630387/9443324/bbbf47e0-4a80-11e5-9dd0-6a3bdafbaee2.png)

**Comment by l3d00m** [comment]
What version are you using? If you're using the play store version, it's already fixed in #161. The newest version will be pushed to play store soon(tm).

**Comment by AmyAmy** [comment]
Apologies, I did search for this issue but didn't find any. Consider the issue closed/duplicate.
