### ISSUE TITLE
In the version 2.0.1 has disappeared the colored nav bar

### ISSUE THREAD

**Issue by luistoluca** [qklabs/qksms#181]
In the version 2.0.1 has disappeared the colored nav bar option on Lollipop and this is a very important feature

**Comment by moezbhatti** [comment]
This feature was removed because it was causing issues on a lot of rooted devices

**Comment by luistoluca** [comment]
and the not root users? its a beautiful feature :/ for this reason i downloaded the app, is the unique sms app with this option

**Comment by luistoluca** [comment]
well, I'll have to use another app or download the 1.12.1 version

**Comment by l3d00m** [comment]
You have to download another app just because the nav bar isn't colored?
