### ISSUE TITLE
QKSMS is not opened from Contacts error is "No app was found to handle this action"

### ISSUE THREAD

**Issue by licaon-kter** [qklabs/qksms#183]
### DESCRIPTION
Using Cyanogenmod 12.1 ( build 2015-08-22 )
QKSMS 2.0.1 from F-Droid

### STEPS
1. Use QKSMS as default SMS app
2. Open Contacts ( *com.android.contacts* )
3. Select a contact
4. Scroll down to a message
5. Tap on the message

### EXPECTED
QKSMS app should open to that person and message

### OBSERVATIONS
If the Cyanogenmod SMS app ( *com.android.mms* ) is NOT disabled it will be opened, although it can't be used since QKSMS is selected as default SMS app.

If the Cyanogenmod SMS app ( *com.android.mms* ) IS disabled a toast appears saying *"No app was found to handle this action"*

**Comment by moezbhatti** [comment]
Confirmed, this happens on my device as well. I wonder if there's a way to find out what intent it's using

I'll look into this now

**Comment by moezbhatti** [comment]
This issue is fixed on the `action-view` branch, though there are some new bugs introduced there that need to be fixed before release

**Comment by licaon-kter** [comment]
Fixed in 2.1.0
