### ISSUE TITLE
No return key on keyboard

### ISSUE THREAD

**Issue by 2016rshah** [qklabs/qksms#184]
When I try to compose a message in the bottom right corner of my keyboard where I typically see a return key to make a new line there is only the button to the emoji keyboard. Why can't I insert a new line into my messages?

I am using Google Keyboard on a Samsung Galaxy S4 running Android 5.0.1

(Sometimes on other apps the keyboard has a return key and if you hold it you will find the key to get to the emojis. Even if I hold down the emoji key I can't find a key to make a new line)

![keyboard_ss](https://cloud.githubusercontent.com/assets/6821244/9500134/b6443ae2-4bf1-11e5-8005-82fff5d7d0b2.png)

**Comment by l3d00m** [comment]
Settings -> General -> Enter Button  
Change to New line (or send). My PR #177 should also fix some issues with this.  
@moezbhatti It's probably better to not use Emojis as the default option for enter button, new line is probably a better default

**Comment by agodlydeciple** [comment]
believe it or not. the emoji key is a 'Feature' of the Google Keyboard and it cannot be disabled. You need to hold the uppercase (alt) button in order for it to change to a 'Enter' button.  I used to use this keyboard as my main one until this happened - so i switched to swift key.  Hope that helps.

**Comment by l3d00m** [comment]
Yeah, it's a feature because the app "says" the keyboard it should use the enter button as emoji key.  
I think when you change it to new line it gets a normal return button.

**Comment by 2016rshah** [comment]
@l3d00m Settings -> General -> Enter Button worked perfectly, thanks!
