### ISSUE TITLE
Notification sound doesn't play when screen off and QKSMS open

### ISSUE THREAD

**Issue by scottjulian** [qklabs/qksms#196]
The notification sound doesn't play when QKSMS app is open and the screen is off with wake phone enabled.

-wake phone: on
-notification: enabled
-notification led: on
-vibration: on
-show ticker: on

device: Samsung Galaxy S6 - g920T
OS: Android 5.1.1

**Comment by moezbhatti** [comment]
Tried testing this using your provided info, but the notification sound still plays for me

Are you still able to reproduce the issue?

**Comment by scottjulian** [comment]
Yes, version 2.0.1. Will upload a video shortly. 

I am able to reproduce this by being in the message view, with the screen off (phone unlocked), and when I receive a message from the same contact that the message view is on, the screen wakes to the message view, but no notification sound is played.

**Comment by scottjulian** [comment]
After some testing and research, this issue seems to be specific to some Samsung devices (S5, S6, Note 4, Note 5, probably some others). After trying other sms clients (textra, chomp, google messages, handcent) this issue is the same across all of them on my S6. And I spoke to a Samsung representative stating that this seems to be a known samsung issue. It is pretty strange, as this issue doesn't exist with Samsung's default messaging app. Closing.

**Comment by moezbhatti** [comment]
Very interesting, thanks for the confirmation
