### ISSUE TITLE
Replace numbers by contact name

### ISSUE THREAD

**Issue by ctodobom** [qklabs/qksms#199]
Sometimes a number is received from a contact and it is already on contact list. It would be great if QKSMS replace the number by the name of the contact and type of number (mobile, home, ...)

This resource is implemented in Chomp SMS and is very useful with cell services that sends SMS messages with missed calls while the phone was unreachable or turned off.

**Comment by sm4rk0** [comment]
This is already defined as an enhancement in #99

**Comment by ctodobom** [comment]
Great, subscribed to that issue.

**Comment by moezbhatti** [comment]
Going to close this as it's a duplicate issue

FYI there is now a PR for this under #205 
It should be merged in the next day or so, just some minor changes to be made

**Comment by ctodobom** [comment]
Just wanting it to appear on f-droid and make my default sms app! thank you!
