### ISSUE TITLE
Send button icon looks like a 'T' instead of a '+' after sending a message

### ISSUE THREAD

**Issue by amitav13** [qklabs/qksms#204]
The animation seems to fail to come back to its initial position after the cross for canceling sending goes away. 

Tested on a Oneplus One, 5.1.1.
![screen shot 2015-09-11 at 1 04 02 pm](https://cloud.githubusercontent.com/assets/7059002/9821076/e509f95c-5885-11e5-882b-e5bad63c06d6.png)

**Comment by moezbhatti** [comment]
This is fixed in 2.1.0, which is currently in the beta channel

**Comment by amitav13** [comment]
Great, thanks!
