### ISSUE TITLE
Use Singleton pattern for ThemeManager

### ISSUE THREAD

**Issue by moezbhatti** [qklabs/qksms#210]
This should help with some views not receiving correct values due to it not being initialized properly

**Comment by Allsimon** [comment]
I'm going to work on this, can you tell me how to reproduce the problem with those views please ?

**Comment by moezbhatti** [comment]
Sorry for late response @Allsimon 

Sometimes if the app is open in the background for a long time, and then QK Reply is opened, it won't be themed properly. I remember there were some other similar cases, most of which I made workarounds for, but this should help prevent anything like that in the future
