### ISSUE TITLE
Need design mocks for audio player

### ISSUE THREAD

**Issue by l3d00m** [qklabs/qksms#212]
Design mockups for audio player and for audio attachments needed. It'd aldo be helpful if i could get one for voice notes. (similiar to whatsapp?) @moezbhatti

**Comment by moezbhatti** [comment]
Oh man I really need to get on this. I'll try and whip something together tomorrow

**Comment by l3d00m** [comment]
That would be nice. I have no idea how to implement the design anyway.

**Comment by moezbhatti** [comment]
Okay, finally, here's a quick mockup 
![device-2015-10-12-142046](https://cloud.githubusercontent.com/assets/4358785/10439964/8b466d26-710b-11e5-87bd-d8d904533d06.png)

**Comment by l3d00m** [comment]
Thanks, i'll try to get it done this week. I'll write you if I need help.

**Comment by moezbhatti** [comment]
Awesome, feel free to reach out any time
