### ISSUE TITLE
Help My Please

### ISSUE THREAD

**Issue by joseliko7** [qklabs/qksms#221]
How do I edit the name of package?

**Comment by l3d00m** [comment]
Did you mean something like [this](http://stackoverflow.com/a/19320896/4026792)?

**Comment by joseliko7** [comment]
Sorry, I was learning before android hehe

I am Spanish , I want to help translating to Spanish .

**Comment by l3d00m** [comment]
The translation files are hosted on [crowdin](https://crowdin.com/project/qksms). Feel free to submit translations there. Thanks for your help. 

Can you close the issue as it is resolved now?

**Comment by joseliko7** [comment]
Yes, Thanks!

**Comment by l3d00m** [comment]
Can be closed
