### ISSUE TITLE
Update Google Play for latest release

### ISSUE THREAD

**Issue by smarquespt** [qklabs/qksms#222]
In Google play, the latest release is 2.0.1. Can you upload the 2.1 release?

Regards

**Comment by l3d00m** [comment]
GPlay also has the 2.1 release, but only for beta testers (because it is beta). F-droid doesn't have different beta or release channels and it automatically is build from the newest release on github, so the fdroid version is 2.1.

**Comment by smarquespt** [comment]
I didn´t knew that. I´ve already joined beta testing group.

Thanks
