### ISSUE TITLE
The "Conversations" label is incorrect after locking and then unlocking my smartphone

### ISSUE THREAD

**Issue by rick9791** [qklabs/qksms#225]
Basically, if I lock my smartphone after leaving a conversation (leading to the conversation list) and then unlock it, the "Conversations" title will display a contact name (from the conversation I initially left).

**Comment by moezbhatti** [comment]
This should be fixed with the merge of `mainactivity-cleanup`

Are you able to compile the project yourself? If not, I can send you an APK and you can test it to confirm

**Comment by rick9791** [comment]
Can't compile, can you send me the APK?

**Comment by moezbhatti** [comment]
Send me an email at moez@qklabs.com and I'll reply with an APK

**Comment by rick9791** [comment]
Sent, I'll be waiting.

**Comment by rick9791** [comment]
Alright, I can confirm that the bug is fixed. Thanks.
