### ISSUE TITLE
Notification ticker text only showing "QKSMS: New message"

### ISSUE THREAD

**Issue by itismark** [qklabs/qksms#230]
App version: 2.2.0
Device: Galaxy S3, 4.4.2

The ticker text when receiving messages no longer shows the message, only "QKSMS: New message." I do not have private notifications enabled.

Expected behaviour:
Show sms message in ticker.

Steps:
* Enable ticker text: SMS notifications - enabled; Show ticker - enabled; Private notifications - show all
* Receive text message
* Watch status bar

![2015-10-23 00 25 06](https://cloud.githubusercontent.com/assets/15256509/10681796/f5998130-78e1-11e5-9cac-52db081900a1.png)

**Comment by l3d00m** [comment]
That's probably my fault, i will fix it today.

**Comment by itismark** [comment]
thank you kind sir 😄

**Comment by l3d00m** [comment]
fixed with #232, means it will be fixed with next release (or you self-compile the newest code)
