### ISSUE TITLE
Extreme battery usage with unread message

### ISSUE THREAD

**Issue by UrzaMTG** [qklabs/qksms#235]
When I have an unread message waiting for me to read it, QKSMS starts to use an insane amount of battery.

**Comment by UrzaMTG** [comment]
http://imgur.com/a/ZgyVD

I received a text message at about 1:30 am that I didn't read until about 9:30 am. My phone was on a wall charger for the entire duration. In the images, you can see QKSMS has a rather large 15% of the usage, and in the battery graph you can see how the charging started to work much better starting at around the time I read the message (I also force killed the QKSMS instance)

**Comment by astrohm** [comment]
I've noticed this as well.

**Comment by licaon-kter** [comment]
Duplicate of https://github.com/qklabs/qksms/issues/198 ?

**Comment by moezbhatti** [comment]
Duplicate
