### ISSUE TITLE
Status bar too dark

### ISSUE THREAD

**Issue by mourningbell** [qklabs/qksms#247]
The QKSMS status bar is too dark. I'm pretty sure this happens 100% of the time for me. Screenshots included compare it with goneMAD media player.

![screenshot_2015-10-26-08-27-29](https://cloud.githubusercontent.com/assets/11153263/10770522/2a16b9ee-7cc2-11e5-9003-37b91a3d9e54.png)
![screenshot_2015-10-26-21-32-35](https://cloud.githubusercontent.com/assets/11153263/10770542/3eae01c8-7cc2-11e5-9a42-de18194b4f0b.png)

**Comment by M2ck** [comment]
Same "darkness" on my device, it's a bug from the [(deprecated) library] (https://github.com/jgilfelt/SystemBarTint) used to implement this feature.

**Comment by moezbhatti** [comment]
Fixed in https://github.com/qklabs/qksms/commit/84c3b0b45e2d272320ccc61bebc159b1d47ebaf6
