### ISSUE TITLE
SMS Scheduler

### ISSUE THREAD

**Issue by smalltock** [qklabs/qksms#262]
It'd be nice to have an inbuilt option to delay a message.

**Comment by moezbhatti** [comment]
Are you talking about delayed or scheduled?

**Comment by smalltock** [comment]
Scheduled. We can already delay, yeah?.

**Comment by moezbhatti** [comment]
Correct, just wanted to confirm

**Comment by smalltock** [comment]
Sorry, I was being unclear

**Comment by moezbhatti** [comment]
In that case it's a duplicate, so I'll close this and we'll use this issue instead: https://github.com/qklabs/qksms/issues/137
