### ISSUE TITLE
New Update v2.2.3 crash on first launch

### ISSUE THREAD

**Issue by miladmaz12** [qklabs/qksms#268]

**Comment by moezbhatti** [comment]
Any information about your device?

**Comment by miladmaz12** [comment]
Nexus 6 - Android 5.1.1

**Comment by moezbhatti** [comment]
Send me an email, I'll send you another build and you can let me know if it crashes

**Comment by moezbhatti** [comment]
moez@qklabs.com

**Comment by miladmaz12** [comment]
Ok. I sent one

**Comment by moezbhatti** [comment]
Fixed in 2.2.4

**Comment by miladmaz12** [comment]
This has been fixed.
