### ISSUE TITLE
[Feature Request] Change background in chat window

### ISSUE THREAD

**Issue by OpenFang** [qklabs/qksms#279]
It would be cool to set a picture as the wallpaper in the message screen

**Comment by licaon-kter** [comment]
...for each contact.

**Comment by licaon-kter** [comment]
Why? :(

**Comment by moezbhatti** [comment]
Sorry, should have added a comment. It just doesn't fit within the design of QKSMS, where everything is simple and flat

**Comment by licaon-kter** [comment]
Ok, at least we have title bar and accent colours to customize, although background colour changing would be nice too.
