### ISSUE TITLE
Action bar tinting issue

### ISSUE THREAD

**Issue by M2ck** [qklabs/qksms#289]
Action bar in Recent apps panel does not comply the selected theme and remains dark.

![screenshot_2015-12-01-11-05-13](https://cloud.githubusercontent.com/assets/6850125/11498004/f5fb2aac-981c-11e5-8ccf-1ad5254c818d.png)

**Comment by moezbhatti** [comment]
Not possible to fix with the current implementation of themes, this would require a pretty big restructure
