### ISSUE TITLE
[feature request] geo: URI scheme

### ISSUE THREAD

**Issue by ghost** [qklabs/qksms#292]
[Geo URI](https://en.wikipedia.org/wiki/Geo_URI_scheme) is a standard way of sharing location information. Supporting it would make clickable a link like geo:37.786971,-122.399677 in a user's preferred maps app.

Here is an example of how it is implemented in [ChatSecure](https://github.com/guardianproject/ChatSecureAndroid/pull/610).

**Comment by eighthave** [comment]
Yes, it is easy to support clickable `geo:` URIs and every map app on Android supports receiving location as a `geo:` URL.  I implemented the ChatSecure stuff, feel free to use my code under whatever free software license you need.

**Comment by triq6** [comment]
I believe #320 includes this
