### ISSUE TITLE
Can't attach picture to mms from Google "Pictures" app.

### ISSUE THREAD

**Issue by bendingtime** [qklabs/qksms#298]
Phone - One Plus One X
Oxygen OS 2.1.4

### DESCRIPTION
Can't attach picture to mms from Google "Pictures" app.

### STEPS
1. Open Google Pictures App,
2. Open Picture,
3. Choose share the picture,
4. Select "Qksms",
5. Qksms opens but there is information that app cant get access to picture

### EXPECTED
Share the content from pictures using mms

### OBSERVATIONS
Everything works fine when you add the same picture tapping "+" sign in qksms app in any conversation.

**Comment by dethstar** [comment]
I think this should also be closed by https://github.com/qklabs/qksms/pull/321 but I don't have google pictures to test.

**Comment by moezbhatti** [comment]
Fixed
