### ISSUE TITLE
Every different  MMS in thread is showing as same single MMS

### ISSUE THREAD

**Issue by Dpaine88** [qklabs/qksms#302]
So I tried out the app tonight.  Sent my gf a few pictures of a new haircut.  There's tons of older pictures in the thread. 

Now,  every single picture in our thread is showing as the same haircut picture.  When I click on any of the pictures it will show the correct one in the new window. 

Issue persists upon reboot. 

Note : it is only the pictures I have sent with the issue.  The pictures I have received show the true image. 

Nexus 5 straight talk

**Comment by Dpaine88** [comment]
Not sure how to edit but it appears a few of the pictures I received are effected by this and are showing as the haircut mms so disregard my note above that it was only sent images.

**Comment by ToNIX-** [comment]
I have the same issue.

Moto G XT1040 running Android 5.1

**Comment by moezbhatti** [comment]
Combining with #92
