### ISSUE TITLE
Option to display direct image links as picture messages

### ISSUE THREAD

**Issue by The0x539** [qklabs/qksms#309]

**Comment by moezbhatti** [comment]
I really really want this to be a thing

**Comment by The0x539** [comment]
What, now that you know about the idea, or you have but can't?

**Comment by moezbhatti** [comment]
It's just always been on the back of my mind, haven't gotten around to doing it yet!

**Comment by dethstar** [comment]
I'd like to work on this

**Comment by moezbhatti** [comment]
You have my blessing!

**Comment by dethstar** [comment]
changes that *should* work but don't can be seen [here](https://github.com/dethstar/qksms/commit/92ce8517580c0dd9c1c2454f0798b169677669c8)

**Comment by moezbhatti** [comment]
Added in https://github.com/qklabs/qksms/commit/7ae7e13b26660e8d63bc046bb4fcca101e3805b9
