### ISSUE TITLE
Drafts can't be opened back

### ISSUE THREAD

**Issue by joallard** [qklabs/qksms#310]
```gherkin
When I write a message to a contact
And I press back
And I press the contact again
Then I do not see my draft
And I see no way of getting my draft back (or any draft)
```

**Comment by moezbhatti** [comment]
Works fine for me. Are you able to do a screen recording of this happening?

**Comment by joallard** [comment]
I'd be glad to, do you recommend an app to do that?

**Comment by moezbhatti** [comment]
Usually I do it through the android developer tools on my computer, so I haven't tried any apps myself. This one looks promising though! - https://play.google.com/store/apps/details?id=com.hecorat.screenrecorder.free

**Comment by fredcooke** [comment]
I get this too. In particular, drafts without a recipient disappear all together. Draft state is also lost on rotate, I assume because of poor state data handling on pause/resume or whatever it's called. That's a separate issue, though. I should report it as such.

**Comment by joallard** [comment]
!!!!!! I just lost a 300-char message, only by slightly swiping right, that is infuriating! I have a very stock install, I can't believe nobody else is getting this even with a recipient. For the video, I just need to do it while keeping some privacy

**Comment by joallard** [comment]
JESUS CHRIST I JUST RETYPED MY MESSAGE AND WITH THE STUPID SWIPE FUNCTION I JUST WIPED IT ONCE MORE HOW STUPID IS THAT

**Comment by moezbhatti** [comment]
Should be fixed in https://github.com/qklabs/qksms/commit/c37088ab2e6b71f775b73e15e4941a20c45b4c5f

**Comment by moezbhatti** [comment]
Closing for now. If it happens after 2.5.3, I'll reopen

**Comment by fredcooke** [comment]
Is your master branch clean with only well tested fixes? And if so, when can we expect a new release?

**Comment by moezbhatti** [comment]
Yeah, master is stable. It's about as well tested as the rest of the app has been. Decent, but obviously could use improvement.

I tested all the cases I could think of with this, and the fix made a lot of sense. I'll push out an update later tonight, it'll mostly be stability fixes

**Comment by fredcooke** [comment]
Awesome, I look forward to it. How quickly will it be in f-droid?

**Comment by moezbhatti** [comment]
When I tag a new release it'll get automatically deployed to f-droid. I'm not sure if it becomes available for download instantly or if it takes a few hours like Google Play though
