### ISSUE TITLE
Compose screen doesn't save drafts

### ISSUE THREAD

**Issue by moezbhatti** [qklabs/qksms#314]
Especially an issue on rotation

**Comment by fredcooke** [comment]
Plus one

**Comment by therob84** [comment]
I can confirm this bug happened at least 3 times in the last week with version 2.5.2 at my Fairphone2 | Android 5.1 with qksms as default app.

1.) Typing text --> receiving an SMS --> click at the notification --> old text just dissaperead and was not saved as draft! Happened for sure 2 times.
2.) Text whily typing a new SMS is lost, after rotating the screen/phone to landscape. No draft, just disappeared. This is already reported here #88

Unfortunately both I could not reproduce right now. I just provoked both scenarios but it did not happen, but both happened unintentedly yesterday!

Any comments whats going wrong and if it will be fixed?
It is a no-go, if a long text just vanishs during composing.....doesn't matter in which circumstances.
Programm should everytime keep the text as draft!

**Comment by moezbhatti** [comment]
Added in https://github.com/qklabs/qksms/commit/aca7fefc6ebd67c1beaaf7ac4d2ba16e152205cc

**Comment by therob84** [comment]
I can confirm that the rotation problem seems to be fixed for v2.5.3.
