### ISSUE TITLE
Enhancement Request: Random color scheme for each conversation at startup

### ISSUE THREAD

**Issue by valerio-bozzolan** [qklabs/qksms#318]
Don't be cruel with this request. You are talking with my girlfriend  :unamused:

Anyway... thanks for this great Free as in Freedom software!

**Comment by licaon-kter** [comment]
Duplicate of https://github.com/qklabs/qksms/issues/301

**Comment by valerio-bozzolan** [comment]
@licaon-kter Sorry no... I'm talking of the screen, not the avatar.

**Comment by licaon-kter** [comment]
my bad.

**Comment by moezbhatti** [comment]
Do you want them random, or user-selectable?

**Comment by valerio-bozzolan** [comment]
(Let me ask to my dear:)

«RANDOM!!!!!!!»

I think random :) Thanks so much.

**Comment by szabolcsx** [comment]
The combination of them would be better I guess: each time when a new conversation is started it gets a random color and the user could change that if it doesn't like.

**Comment by valerio-bozzolan** [comment]
+1 for @szabolcsx

**Comment by xavihernandez** [comment]
duplicate of #133
