### ISSUE TITLE
MMS auto config message like a small dog humping a leg

### ISSUE THREAD

**Issue by fredcooke** [qklabs/qksms#327]
I checked the box. Some time went by. First pop up about success. OK. Some time went by. Many many more of the same pop up (seconds apart and in bursts). Hard to dismiss due to layering issues in and out of the app. Fresh install likely required to show this.

**Comment by fredcooke** [comment]
This has not recurred, FWIW.

**Comment by fredcooke** [comment]
Did you ever find or fix this? Or has it simply not been reported by anyone else? I said it has no recurred, but it is a first install thing, so it will never recur for me, unless I put QK on a new phone. Just curious, as it'd be a shame to see others burned by it. On the other hand, enough might have changed to remove the behaviour incidentally.

**Comment by moezbhatti** [comment]
@fredcooke couldn't repro it, and never ended up having any other reports. I think you're right, changing something else might have fixed this accidentally
