### ISSUE TITLE
Muting/unmuting a conversation should show a toast and vibrate

### ISSUE THREAD

**Issue by moezbhatti** [qklabs/qksms#330]
Currently it's not very clear that anything actually happened, when you press the button

**Comment by redwerk** [comment]
Hi @moezbhatti , i am interesting in the implementation of this feature and if i understand correctly, this functionality should be added into [this method] (https://github.com/qklabs/qksms/blob/18abeb4e2986ac25c2bdbf9a86c7134f895dc6df/QKSMS/src/main/java/com/moez/QKSMS/ui/messagelist/MessageListFragment.java#L481) ?

**Comment by moezbhatti** [comment]
@redwerk sorry, haven't been very active with QKSMS over the last few days. That's right, it'll go there!
