### ISSUE TITLE
Popup SMS doesn't extend

### ISSUE THREAD

**Issue by sheitoons** [qklabs/qksms#333]
I'm running the latest version (from the play store) which is 2.4.1 on a Nexus 5 first gen, running latest android 6.0.1.
I'm using QKSMS and I've noticed that, the popup doesn't extend while I try to extend in order to see more thant the new sms.

The problem is that when I try to extend the popup, the app shutdown and I have to re-open it again and go through the app to view all the messages.

**Comment by moezbhatti** [comment]
Are you able to get a logcat of the crash?

**Comment by sheitoons** [comment]
Hi,

I've just checked if the popup extend. And since the last update I can
extend it.

Thanks for your support

**Comment by moezbhatti** [comment]
Perfect
