### ISSUE TITLE
Reply and Mark as Read icons on Android Wear

### ISSUE THREAD

**Issue by fcastilloec** [qklabs/qksms#334]
There isn't an specific icon on Android Wear for any of the functions, it's just a plain color circle (in my case) or square. I think that there should be a symbol of something related to mark-as-read (a check mark) and reply (an arrow).
I'm attaching some screenshots to show the problem.
![mark_read](https://cloud.githubusercontent.com/assets/1280530/12126554/de8a2c6a-b3bf-11e5-80a9-27141f1b2023.png)
![reply](https://cloud.githubusercontent.com/assets/1280530/12126555/de8a5762-b3bf-11e5-9671-7dd3b544986f.png)

**Comment by nikjft** [comment]
Confirmed on Huawei Watch.

**Comment by fcastilloec** [comment]
I recently received the Marshmallow update for my Huawei Watch and this bug is still present. I don't understand why it's labeled as "needs repro" when @nikjft has already confirm the issue.
Maybe @moezbhatti doesn't have the watch to reproduce the bug, but he should trust us that the bug is there and it's very annoying.

**Comment by moezbhatti** [comment]
Fixed the label
Although yes, I don't have my own android wear watch, so I can't confirm/test/fix this myself

**Comment by moezbhatti** [comment]
And sorry about the label issue - I renamed the labels and defaulted bugs to be `bug: needs repro`

**Comment by moezbhatti** [comment]
http://stackoverflow.com/questions/33078751/android-wear-vector-drawable-not-visible-on-real-device
