### ISSUE TITLE
Disable phone sound when headphone / headset is connected

### ISSUE THREAD

**Issue by Noctiflore** [qklabs/qksms#339]
When a headphone or headset is connected (either wired or Bluetooth), in sound mode, SMS notification sounds are played by both internal speaker and headphone.

Internal speaker should be disabled (or there might be an option to achieve that).
Tested in 2.4.1 and 2.2.4 with Android 4.4.2.

**Comment by licaon-kter** [comment]
This might be an Android thing, although might seem wrong, forgetting headphones plugged in makes your phone silent, which is bad.

**Comment by moezbhatti** [comment]
Yeah, sounds like an android issue more than anything. If someone knows better, feel free to comment
