### ISSUE TITLE
Update About tab

### ISSUE THREAD

**Issue by M2ck** [qklabs/qksms#341]
Add Google+ community, GitHub & Crowdin links into About tab.

[https://plus.google.com/communities/104505769539048913485](https://plus.google.com/communities/104505769539048913485)
[https://github.com/qklabs/qksms](https://github.com/qklabs/qksms)
[https://crowdin.com/project/qksms](https://crowdin.com/project/qksms)

**Comment by redwerk** [comment]
Hi, i could do the pull request if no one develops this issue.

**Comment by M2ck** [comment]
Thanks @redwerk
