### ISSUE TITLE
Moto Display notifications aren't working

### ISSUE THREAD

**Issue by moezbhatti** [qklabs/qksms#343]
If anyone has a phone that supports Moto Display, let me know and we can work together to fix this one

**Comment by sm4rk0** [comment]
How can I help?

**Comment by moezbhatti** [comment]
Can you confirm that QKSMS notifications aren't showing up in Moto Display?

**Comment by sm4rk0** [comment]
Yes:
![tmp_27252-img_20160107_181424-445574619](https://cloud.githubusercontent.com/assets/1700941/12177293/9c697694-b56b-11e5-8982-fbd7336bc5e9.jpg)
The icon (when it's there) is always white on black background.
There must be a guideline from Motorola about this...

**Comment by sm4rk0** [comment]
Only the icon is missing. The rest (contact name and picture, message preview) is there, like displayed [here](https://www.motorola.com/us/Moto-X-Features-Active-Display/motox-features-3-active-display.html).

**Comment by moezbhatti** [comment]
Ahh okay, I think I know why this is happening

**Comment by moezbhatti** [comment]
Fixed https://github.com/qklabs/qksms/commit/f0b3f5f461e2901e73c7a87a0b3bc8a55f3d90d8
