### ISSUE TITLE
Gfx weirdness in "go back" animation

### ISSUE THREAD

**Issue by tp0** [qklabs/qksms#350]
When going back to the message list view from any view (message content view, main settings) by pressing soft back key, on the left side there appears a weird graphical glitch during the animation. It looks like something is drawn incorrectly in the animation. Some sort of brief vertical bar/line flash (not great description).

I _think_ this appeared after the latest updated (Jan 7: v2.5.1).

Unfortunately I don't have another device so I can't take a video and direct screen recorders do not show the glitch properly.

Motorola Moto G 3rd Gen
Lollipop 5.1.1
QKSMS 2.5.1

**Comment by tp0** [comment]
2.5.3 (from F-Droid) seems to have fixed this glitch, but the animation isn't very smooth at least on my phone and as a result the intentional material-like border design does not look as good as it should.

**Comment by moezbhatti** [comment]
Alright. Well that's a separate issue so I'll close this one
