### ISSUE TITLE
App aggressively hides timestamps

### ISSUE THREAD

**Issue by fredcooke** [qklabs/qksms#358]
To the point of unrelated conversations hour(s) apart being clumped together with a single time stamp. I would MUCH prefer to see the to the minute or second stamp on every message. This would lead to a more visually stable interface, too, not chopping and changing screen positions as it sees fit.

**Comment by xavihernandez** [comment]
I was about to report this issue too. Hidden timestamp on recipients' messages are a pain. We have to tap on messages to be able to see when they were received. Timestamp should be on all messages

**Comment by fredcooke** [comment]
I was thinking about this the other day as I was using it and noticed an hour of stuff with one stamp at the bottom and thought: If the clumpiness was tunable I would set it to 1 minute max between first and last AND I would want the first and last to BOTH display stamps including seconds with only the ones in between hidden. However I'd still prefer not to hide any, just like Xavi.

**Comment by moezbhatti** [comment]
A lot of people have been asking about this recently

I'll make the hidden timestamps configurable

**Comment by xavihernandez** [comment]
Thabls @moezbhatti

**Comment by moezbhatti** [comment]
Added in 44afddb

**Comment by moezbhatti** [comment]
Fixed in 2.6.1
