### ISSUE TITLE
Base screen spends too much space on circles with letters

### ISSUE THREAD

**Issue by fredcooke** [qklabs/qksms#361]
And insufficient on name, draft, message start/teaser, time. I know this is on purpose, as are some other bugs I've filed, but it feels like there could be a bit less grey around the sides of the circles?

**Comment by moezbhatti** [comment]
Main reason for that is that ideally it'll be showing photos for your contacts, which do deserve the real estate

**Comment by fredcooke** [comment]
Where do you source the photos from? Mine has exactly no photos and is likely to stay that way. How about a "no circle/photo at all" option?

**Comment by moezbhatti** [comment]
There's an option for this in the appearance settings :)
