### ISSUE TITLE
Enhancement Request: Sent Time for Messages

### ISSUE THREAD

**Issue by arranf** [qklabs/qksms#37]
Messages display the "received time" but "sent time" is much more useful for figuring out if you should have picked up a message earlier.

**Comment by srcreigh** [comment]
Ehhh not sure about this. Received time is pretty standard, and you can always just click through to see sent time.

@moezbhatti feel free to reopen.

**Comment by arranf** [comment]
Sorry!
I meant to specify click through sent checking on MMS

**Comment by Blupi** [comment]
I'd like this bug to be reopen and put as enhancement. It was an option setting on 8sms, the previous app I used.
As arranf said, I consider the sent time much more relevant than the time the text was received by my phone (even though occasionaly sender can be in a different time zone).
Clicking every text to see it is tedious.

**Comment by homersimpsons** [comment]
Would be Great, Just a checkbox in Option to choose which date to show

**Comment by moezbhatti** [comment]
Added in 44afddb
