### ISSUE TITLE
[Feature] Differ between send to MSC and recipient

### ISSUE THREAD

**Issue by dkadioglu** [qklabs/qksms#370]
It would be nice, if there would be one check mark when the SMS has been delivered to the MSC and a second one when it has been delivered to the device of the recipient.

Thanks in advance!

**Comment by moezbhatti** [comment]
If the message doesn't say "Sending" or "Failed" then it means it was successfully sent

**Comment by dkadioglu** [comment]
Thanks for your reply. Let me try to go a bit more into detail: at the moment, I have to open the message details (press on a message I've sent) to differ between:
- The message has been accepted by the MSC but, as the recipients device is not reachable (switched off, no network coverage, etc.), has not been delivered to the recipients device.
- The message has been accepted by the MSC and has been delivered to the recipients device - i.e. the delivery report for this SMS has been received.
In both cases there is a check mark next to the timestamp which is irritating in my opinion. The necessity to open the message details and the double meaning of the check mark are the reasons, why I am asking for an improvement. If not two check marks, maybe then still just one which only appears when the SMS delivery report has been received.
Another thing is, that the toast message "Message delivered" appears twice per SMS: the first time when the message has been delivered to the MSC and the second time when the message has been delivered to the recipients device (as far as I can tell).
I apologise for asking again but, I am very interested in your arguments against this.

**Comment by dkadioglu** [comment]
Just saw that Textra SMS has that feature and shows two check marks: https://lh3.googleusercontent.com/rjtyFn1H6h3AKz8no5Ud_2DKXfoxrSRLR3-eom-ZqqHk-VUDZFqm32gwjZmyrU-KodqU=h900

I would be happy if you could think about implementing this again. And I am still interested in your opinion about that.

**Comment by moezbhatti** [comment]
Sorry for the late response

Alright, I'll definitely look into this some more. I think you may be onto something. I was under the impression that a delivery callback would only occur once it's been delivered to the recipient, but it's possible that it's actually two different stages of delivery

**Comment by dkadioglu** [comment]
Thanks for looking into this! Have you already had the opportunity to investigate this?

**Comment by rodeusdi** [comment]
I would be happy if you would implement this feature, too. Qksms is a very good app, but without differing between the successfully sending of a sms and the delivery of it to the recipient's device I miss an important property.
