### ISSUE TITLE
"Version 2.5.1 requires Android 4.0.3 or newer", could not be installed on Android 4.4.2

### ISSUE THREAD

**Issue by davidhedlund** [qklabs/qksms#372]
QKSMS on https://f-droid.org/repository/browse/?fdfilter=qksms&fdid=com.moez.QKSMS says:
Version 2.5.1 - Added on 2016-01-08
This version requires Android 4.0.3 or newer.

I use Android 4.4.2 but cannot install it?

**Comment by moezbhatti** [comment]
Are you still seeing this issue?

**Comment by davidhedlund** [comment]
@moezbhatti No. Thank you for fixing this.
