### ISSUE TITLE
Read messages

### ISSUE THREAD

**Issue by mpowell38** [qklabs/qksms#38]
I cannot get read messages to be marked as read. Other people are having the same problem. I have reported this several times.

**Comment by moezbhatti** [comment]
How long has this been happening for you?

**Comment by mpowell38** [comment]
Around March 4th.I have uninstalled several times and reinstalled just to see if I could get it to work.

**Comment by moezbhatti** [comment]
Does it occur every time or seemingly at random?

**Comment by mpowell38** [comment]
Every time.

**Comment by moezbhatti** [comment]
Is QK set as your default messaging app?

**Comment by mpowell38** [comment]
Yes.It is, it was working fine but now it looks like my phone stock sms is messing with it. I am not sure why .

**Comment by srcreigh** [comment]
I can repro it. @moezbhatti try this out:

1. Mark a conversation as unread in the app.
2. Press the home button.
3. Pull down on the heads up notification to open the notifications drawer.
4. Tap on the main part of the notification, i.e. not the buttons.
5. Close the conversation via the back button.

Expected:
The conversation is marked as read.

Actual:
The conversation is marked as unread. Furthermore, opening and closing the conversation again doesn't change the read state.

**Comment by moezbhatti** [comment]
Happens for me too. Although if I open a different conversation, then this again, it gets marked read

**Comment by srcreigh** [comment]
Yup. But the bug is that it should be marked as read from the start. We have a repro so we can fix it. :-)

**Comment by mpowell38** [comment]
Thank you for looking into this.

**Comment by Yefssy** [comment]
I'm having a similar issue. Sometimes a message doesn't mark it self read when I click on the conversation.
