### ISSUE TITLE
sliding side panel

### ISSUE THREAD

**Issue by mpowell38** [qklabs/qksms#39]
I cannot find the options to hide the side sliding panel. I have had other people tell where it is located but for some reason I cannot find it on mine. I have looked at every options. Thank you.

**Comment by moezbhatti** [comment]
Can you upload a screenshot at the bottom of the general settings?

**Comment by mpowell38** [comment]
![screenshot_2015-03-19-11-10-07](https://cloud.githubusercontent.com/assets/11544915/6733485/d3df3332-ce28-11e4-9fec-25405be6b819.png)

**Comment by srcreigh** [comment]
It's actually at the bottom of the Appearance settings. :-)

**Comment by mpowell38** [comment]
![screenshot_2015-03-19-11-19-09](https://cloud.githubusercontent.com/assets/11544915/6733654/d7e79888-ce29-11e4-8d77-8301561bb2dd.png)

**Comment by moezbhatti** [comment]
There's nothing below this?

**Comment by moezbhatti** [comment]
Right, appearance not general

**Comment by mpowell38** [comment]
No it stops there.

**Comment by moezbhatti** [comment]
Definitely a bug, there should be like 4 more options there.

What version of android are you running? Can you give some info about your device?

**Comment by mpowell38** [comment]
android 4.3  it is a ZTE Quartz it is on straight talk wireless.

**Comment by moezbhatti** [comment]
Cool, thanks for the report. I'll check this out tonight

**Comment by mpowell38** [comment]
Thank you so much. I hate being a bother, but I do love your app.

**Comment by moezbhatti** [comment]
Not a bother, you're helping us make it better! :smile:

**Comment by anubiann00b** [comment]
I'm still don't see those options... In the Appearance menu, the last group is Avatars with 3 options (Hide conversation avatars, hide sent message avatars, and hide recieved message avatars).

**Comment by moezbhatti** [comment]
This was fixed by @srcreigh
