### ISSUE TITLE
Can't select sms with numbers inside bug

### ISSUE THREAD

**Issue by cirelli94-unimib** [qklabs/qksms#392]
When I try to select an sms to open "Option message" view, if there is a number, like a telephone number or something like that, which is highlighted, the "Option message" view doesn't appear!
It appears only if I select the row but outside the window of the message. 
This is surely a problem if the message is very long and there isn't the contact icon so there's not a lot of place to select the row!

**Comment by sm4rk0** [comment]
Duplicate of #171?

**Comment by cirelli94-unimib** [comment]
Yes! I'm sorry
