### ISSUE TITLE
messages hidden when composing by searching a contact

### ISSUE THREAD

**Issue by srisl** [qklabs/qksms#400]
hello , 

first of all this is a great sms app. I using this for few months.  but the latest version   when I search a contact and then compose sms using that searched contact. sent sms dosen't show anything. but  when I click back and the looking up sms thread with my contact name. it shows all the sent & received sms.

**Comment by therob84** [comment]
Hm...funnyly it seems connected to my ticket, open also just some hours ago: #398 
Only difference seems, that I can't finde this message anymore afterwards...

**Comment by srisl** [comment]
yep

**Comment by moezbhatti** [comment]
Should be fixed in https://github.com/qklabs/qksms/commit/4a2e53606b314f156edff638233b33cd1c054ba6
