### ISSUE TITLE
[IMPROVEMENT] Add "Call" to Wear SMS actions

### ISSUE THREAD

**Issue by matejdro** [qklabs/qksms#401]
When you receive SMS, QKSMS will display "Reply" and "Mark as Read" actions on the notification.

It would be useful if "Call" action would be added to this set.

**Comment by moezbhatti** [comment]
Actually, this feature does exist. You can add a "Call" action to the notification in the settings. Let me know if this addresses your issue

**Comment by matejdro** [comment]
Oh wow I did not even notice that, thanks!

Wait, if the feature is already in, what was commit by redwerk for?

**Comment by moezbhatti** [comment]
I don't think he noticed that the setting was already there, and then added the call button the notifications again :)
