### ISSUE TITLE
Location Permisions

### ISSUE THREAD

**Issue by ghost1372** [qklabs/qksms#408]
hi,Please tell me which of the following permisions to what? and why qksms need it?tnx

    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

**Comment by moezbhatti** [comment]
Doesn't use it for anything currently. The intention was to eventually be able to send your location via SMS
