### ISSUE TITLE
[BUG] After sending a new message with "+", screen turns empty (but should show history or main screen)

### ISSUE THREAD

**Issue by therob84** [qklabs/qksms#411]
### DESCRIPTION
If composing a new message for an existing contact, after the message was sent qksms stays in the composing window but it is completely empty.
Could be connected to #396 and #397 

### STEPS
1. Click "+" to compose a new SMS
2. select a contact (from which a history should be available, but is not loaded, reported in #397) 
3. type a message + click send

### EXPECTED
qksms should either load and display the history of the contact's conversation after sending (#397)
OR
qksms should switch to the message main screen

### OBSERVATIONS
The screen becomes completely empty. 
Only the contact's name is displayed, but neither the conversation history, nor even the recently sent message is visible!

Tested with v2.5.2

**Comment by therob84** [comment]
Seems to be solved for current v2.5.3 of today - can you confirm this?

**Comment by cirelli94** [comment]
I confirm it's solved!
