### ISSUE TITLE
Message Options not accessible

### ISSUE THREAD

**Issue by AScully24** [qklabs/qksms#417]
### DESCRIPTION
Message options are not a accessible when message SMS message contains a hyperlink or a phone number.

### STEPS
1. Open a conversation.
2. Long press a message containing a hyperlink or phone number.

### EXPECTED
Popup box containing message options should appear.

### OBSERVATIONS
No message option dialog appears. No indication that it is accessible.

**Comment by AScully24** [comment]
Additional Info:
Smartphone: Vodaphone Smart Ultra 6
Android Version: 5.1.1

**Comment by sm4rk0** [comment]
Duplicate of #171

**Comment by AScully24** [comment]
Missed that one. Apologies. Closing issue.
