### ISSUE TITLE
Conversation is blank after selecting from the search Result

### ISSUE THREAD

**Issue by romelemperado** [qklabs/qksms#419]
### DESCRIPTION
Conversation is blank after selecting from the search Result.

### STEPS
1. Search a message
2. Select from any of the result

### EXPECTED
After selecting the conversation is blank

### OBSERVATIONS
It looks like the conversation wasn't selected because if you try to reply it will tell you that you need some contacts to send the message..

**Comment by romelemperado** [comment]
Additional info:

Device: Nexus 6p Android 6.0.1

**Comment by moezbhatti** [comment]
Which version of the app are you on?

**Comment by romelemperado** [comment]
2.5.2 The  one in Playstore now..

**Comment by moezbhatti** [comment]
Ah okay. This was actually fixed in 2.5.3, it just hasn't been released to all users yet because it introduces a new and pretty annoying bug. This will be fixed for you once 2.5.4 is released

**Comment by romelemperado** [comment]
Thank you so much..
