### ISSUE TITLE
Upload latest source files to crowdin

### ISSUE THREAD

**Issue by smarquespt** [qklabs/qksms#425]
@moezbhatti 

Hi moez

Can you please upload latest source file to crowdin? I´ve seen some changes in source file that were not uploaded to crowdin. And subsequently merge latest changes to source code. I´ts been a while since you merged strings. As you stated in readme file, pull requests will not be accepted so please before any release do a merge with source code.

**Comment by moezbhatti** [comment]
Absolutely. It's just a matter of remembering for me. I'll update it tomorrow
