### ISSUE TITLE
Samsung multi-window support

### ISSUE THREAD

**Issue by moezbhatti** [qklabs/qksms#436]

**Comment by Allsimon** [comment]
Is it really useful when it will probably be deprecated in favor of Android N multi-window ?

**Comment by moezbhatti** [comment]
I'd say so. It's going to be almost a year before that happens, and even when it does, most of the devices in people's hands will remain on older version. Plus, it's only a few lines of code anyway

**Comment by moezbhatti** [comment]
Released in 2.5.5
