### ISSUE TITLE
Sending group messages while connected to wifi not working

### ISSUE THREAD

**Issue by W1nks** [qklabs/qksms#440]
### DESCRIPTION
When sending group messages while I am connected to Wifi the messages just get stuck on "sending".  I have the "Automatic data" option turned on.  This happened on my Galaxy S4 (5.0.1) and now my new Galaxy S7 (Marshmallow).  I am on Verizon Wireless.

### STEPS
1. Connect to Wifi
2. Send group message
3. Turning off wifi before sending the message or rebooting after trying usually gets the message to go through.

### EXPECTED
The message to go through immediately without any problems.

### OBSERVATIONS
The message hangs on "sending".  I usually then try turning off my wifi and waiting to see if it goes through.  If it doesn't I will reboot my phone then it usually goes.

**Comment by moezbhatti** [comment]
Merging with #49
