### ISSUE TITLE
rotating to landscape orientation closes opened conversation

### ISSUE THREAD

**Issue by billic** [qklabs/qksms#443]
### DESCRIPTION
QKSMS 2.5.4
Opened conversation closed after switching orientation

### STEPS

1. in portrait orientation open conversation, type text and do not send 
![s60316-105048](https://cloud.githubusercontent.com/assets/17784709/13805442/dbcb537c-eb65-11e5-8b80-831fc90c195e.jpg)

2. rotate to landscape -- conversation text disappears (old messages and typed message) and message receiver disappears too (img) (notification says: draft was saved)
![s60316-105058](https://cloud.githubusercontent.com/assets/17784709/13805453/ec9eed12-eb65-11e5-8c57-1fc0fec1a658.jpg)

3. rotate back to portrait returns back typed message, but no conversation are opened anymore. 
![s60316-105615](https://cloud.githubusercontent.com/assets/17784709/13805464/f816a284-eb65-11e5-9f5e-3d886fe8bf13.jpg)

### EXPECTED
same conversation with same typed text in it

### OBSERVATIONS
empty conversation without text in it

from [here](https://github.com/qklabs/qksms/issues/88#issuecomment-196193266)

**Comment by moezbhatti** [comment]
This should be fixed as of version 2.6

**Comment by billic** [comment]
Yes. This issue fixed in my 2.6.1 from f-droid, because I can't switch screen orientation at all. Is this ok?
