### ISSUE TITLE
Marking conversations as read from notification doesn't dismiss notifications.

### ISSUE THREAD

**Issue by srcreigh** [qklabs/qksms#444]
### DESCRIPTION
Marking conversations as read via "Read" button in a notification sometimes doesn't dismiss the notification.

**todo**: this only doesn't work sometimes. need to figure out when it doesn't work. it does work, for example, if i send a message to myself and mark that message as read from a notification. possible cases:

- if there was an unread message above the new message
- if the message above the new message wasn't from you

### STEPS
1. Have Android 5.0 Lollipop
2. Get a notification for an SMS
3. Press "Read"

### EXPECTED
The messaged is marked as read and the notification is dismissed.

### OBSERVATIONS
The notification isn't dismissed.

**Comment by fcastilloec** [comment]
I have encounter this too, but it's very random and hard to reproduce exactly.
I can add that I've seen this also happen from Android Wear, where I get a error message that the action couldn't be done and try again later.
