### ISSUE TITLE
QKSMS calling last conversation opened by itself

### ISSUE THREAD

**Issue by Aichan** [qklabs/qksms#452]
### DESCRIPTION
When app is left in a conversation and screen is turned off, QKSMS often calls the person of the conversation. A reboot seems to fix this issue temporarily 

### STEPS
1. Open a conversation
2. Send or receive message (Not sure if necessary step)
3. Lock your phone with the conversation still opened
4. With screen turned off, sometimes the phone starts to call the person by itself

### EXPECTED
Not calling anyone without pressing the call button

### OBSERVATIONS
Phone is calling people while in pocket, on desk, etc... (Without touching it)

**Comment by Aichan** [comment]
I found what was causing it : I had the "Proximity Sensor" option enabled and it thought I was putting it to my ear when it was in my pocket or when I would put my hand above (I guess?) 

If that matters the phone is a OnePlus One

**Comment by moezbhatti** [comment]
Yeah, seems to be a common mistake :)

Although, the feature definitely should be smarter and not do this if it's laying flat
