### ISSUE TITLE
Notifications are blocked by Android 5 "interruptions" setting

### ISSUE THREAD

**Issue by sm4rk0** [qklabs/qksms#457]
### DESCRIPTION
If "When calls and notifications arrive" option in Android 5 (Settings -> Sound & Notification -> Interruptions) is set to "Allow only priority interruptions" and an SMS from a starred contact is received while in a downtime, there will be no sound.

### STEPS TO REPRODUCE
1. Set "When calls and notifications arrive" to "Allow only priority interruptions"
2. Set the notifications mode to "Starred contacts only" (volume up or down -> tap on star)
3. Make sure "Messages" option is enabled in "Priority interruptions"
4. Star a contact
5. Receive an SMS from a starred contact

### EXPECTED
Notification sound is played.

### OBSERVATIONS
No notification sound is played.

### ROOT CAUSE ANALYSIS:
Possible solution could be using [NotificationCompat.Builder.addPerson()](https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html#addPerson%28java.lang.String%29)

Also, it could be useful to set a category to [Notification.CATEGORY_MESSAGE](https://developer.android.com/reference/android/app/Notification.html#CATEGORY_MESSAGE) by using [NotificationCompat.Builder.setCategory()](https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html#setCategory%28java.lang.String%29)

**Comment by moezbhatti** [comment]
Merging with #326
