### ISSUE TITLE
[Idea] make an API to send sms

### ISSUE THREAD

**Issue by Preovaleo** [qklabs/qksms#459]
Hi,

# What i want to do ?
I want to sync my sms and send some with a 3rd party open source website.

# How ?
1. I see that you already support the Yappi API. So we can use this API and just change the URL that you use to sync. You can defined anything you want and be a standard. (The easiest)
2. You can make something to authorize local app to send sms. Because they can access to other info.

Regards,

**Comment by moezbhatti** [comment]
This is built into Android, using the Intent system
