### ISSUE TITLE
Message details miss spaces in italian

### ISSUE THREAD

**Issue by cirelli94** [qklabs/qksms#466]
### DESCRIPTION
Message details miss spaces in italian so they result bad formatted.

### STEPS
You must have italian language on your phone.

Enter in a conversation
Press long a message
Choose "view details" (obviously, in italian is "mostra dettagli")

### EXPECTED
Message details have spaces between the type of informations and the informations.

ITA (the wrong one)
![media-20160401](https://cloud.githubusercontent.com/assets/1636493/14217267/4e26f91e-f84d-11e5-848a-02a21b3f489a.png)

ENG (the right one)
![media-20160401 1](https://cloud.githubusercontent.com/assets/1636493/14217268/4e769e60-f84d-11e5-878c-14ae48d4bc1b.png)

### OBSERVATIONS
Must add a space.

**Comment by cirelli94** [comment]
I think the problem is here:
qksms/QKSMS/src/main/java/com/moez/QKSMS/common/utils/MessageUtils.java
https://github.com/qklabs/qksms/blob/18abeb4e2986ac25c2bdbf9a86c7134f895dc6df/QKSMS/src/main/java/com/moez/QKSMS/common/utils/MessageUtils.java
at line 714 in method:
private static String getTextMessageDetails(Context context, Cursor cursor)

and better, in some differences between english and italian strings! But, can't undestand what the call res.getString(R.string.message_type_label) do.. in line 721.
If I understand this I should solve this bug by myself and make a pull request!

**Comment by cirelli94** [comment]
ok, I mistake, this isn't closed!

**Comment by M2ck** [comment]
Wrong italian translations, "\u000A" character is missing.

Links for fix them on Crowdin below:
[https://crowdin.com/translate/qksms/1/enca-it#364](https://crowdin.com/translate/qksms/1/enca-it#364)
[https://crowdin.com/translate/qksms/1/enca-it#365](https://crowdin.com/translate/qksms/1/enca-it#365)
[https://crowdin.com/translate/qksms/1/enca-it#366](https://crowdin.com/translate/qksms/1/enca-it#366)
[https://crowdin.com/translate/qksms/1/enca-it#367](https://crowdin.com/translate/qksms/1/enca-it#367)
[https://crowdin.com/translate/qksms/1/enca-it#368](https://crowdin.com/translate/qksms/1/enca-it#368)
[https://crowdin.com/translate/qksms/1/enca-it#369](https://crowdin.com/translate/qksms/1/enca-it#369)
[https://crowdin.com/translate/qksms/1/enca-it#370](https://crowdin.com/translate/qksms/1/enca-it#370)
[https://crowdin.com/translate/qksms/1/enca-it#371](https://crowdin.com/translate/qksms/1/enca-it#371)
[https://crowdin.com/translate/qksms/1/enca-it#372](https://crowdin.com/translate/qksms/1/enca-it#372)
[https://crowdin.com/translate/qksms/1/enca-it#373](https://crowdin.com/translate/qksms/1/enca-it#373)
[https://crowdin.com/translate/qksms/1/enca-it#374](https://crowdin.com/translate/qksms/1/enca-it#374)
[https://crowdin.com/translate/qksms/1/enca-it#375](https://crowdin.com/translate/qksms/1/enca-it#375)

**Comment by cirelli94** [comment]
Thanks, I correct translations, that's fine.
Do you know when this will be updated?

**Comment by M2ck** [comment]
No idea sorry but QKSMS receives regular updates anyway.
