### ISSUE TITLE
Compose Window takes over after rotate from a conversation 

### ISSUE THREAD

**Issue by romelemperado** [qklabs/qksms#469]
### DESCRIPTION
Compose Window takes over after rotate from a conversation 

### STEPS
1. Open any conversation
2. Rotate(Of course auto rotation should be enabled) your phone.
3. After first rotate you will see window is blank 
4. rotate again and you are now on the compose screen/window.

### EXPECTED
Expected behavior is you should stay on the opened conversation even after multiple rotation..

**Comment by romelemperado** [comment]
Device:
Samsung galaxy s3
Android 4.4.4

**Comment by eefret** [comment]
I can confirm the same in a OnePlusOne with 5.1.1
