### ISSUE TITLE
Auto close QK Reply when App is open in foreground

### ISSUE THREAD

**Issue by maglax** [qklabs/qksms#471]
Device: LG V10 T-Mobile
Android Version: 5.1.1
Software version: H90110c
App version: 2.5.5

If QKSMS is open in the foreground when the phone is unlocked after reciving a text, the QK Reply window is overlaid on top of the app itself. Also when the reply overlay is closed, via taping outside the overlay, the app studders.

**Comment by moezbhatti** [comment]
Combining with #293
