### ISSUE TITLE
Web app

### ISSUE THREAD

**Issue by DenBeke** [qklabs/qksms#475]
Ever thought of making a web app like Whatsapp web, so people can send messages from their computer?

**Comment by moezbhatti** [comment]
Would be really awesome, but it's not something I have the knowledge/time to implement. Luckily, Pushbullet provides this functionality!

**Comment by moezbhatti** [comment]
I recommend downloading the android app and chrome extension - https://www.pushbullet.com/

This is what I use myself

**Comment by DenBeke** [comment]
Thanks for the answer!
