### ISSUE TITLE
Dual SIM  Support

### ISSUE THREAD

**Issue by romelemperado** [qklabs/qksms#480]
This is a very beautiful app and i hope dual sim support will come out soon...

**Comment by sm4rk0** [comment]
I agree, but opening an issue before checking if someone already opened a similar or the same one: #207, #381 is not getting us there (on the contrary).

**Comment by rugk** [comment]
As this is a duplicate why have you reopened the issue?

**Comment by romelemperado** [comment]
all other related issues were closed so I reopened this one..

**Comment by sm4rk0** [comment]
The oldest one, #207 is still open, so this one can be closed.

**Comment by romelemperado** [comment]
Closing..
