### ISSUE TITLE
ClassCastException on "Delete conversations" from within the conversation

### ISSUE THREAD

**Issue by sm4rk0** [qklabs/qksms#482]
### DESCRIPTION
As described in the title. Check the [logcat](https://gist.github.com/sm4rk0/b854d0436b8ab9894b20553fc2ce0734).

QKSMS 2.6.0
Moto X
Android 5.1
Xposed framework with some modules, including XPrivacy

### STEPS
1. Open a conversation
2. Tap menu/overflow (three vertical dots)
3. Tap "Delete conversations"

### EXPECTED
Confirmation dialog.

### OBSERVATIONS
"Unfortunately, QKSMS has stopped"

**Comment by moezbhatti** [comment]
Has been fixed for the 2.6.1 release
