### ISSUE TITLE
noAnalytics now requires crashlytics

### ISSUE THREAD

**Issue by mvdan** [qklabs/qksms#484]
See https://f-droid.org/wiki/page/com.moez.QKSMS/lastbuild_128:

```
QKSMS/src/main/java/com/moez/QKSMS/ui/messagelist/MessageListActivity.java:11: error: package com.crashlytics.android does not exist
import com.crashlytics.android.Crashlytics;
                              ^
```

This was when building the `noAnalytics` flavour, with all the analytics dependency lines from `build.gradle` removed. Seems pretty obvious, as this file is in `src/main/java`.

**Comment by moezbhatti** [comment]
Will fix this for the next release

**Comment by mvdan** [comment]
Cool. We'll have that one in the repo then :)
