### ISSUE TITLE
Option to forward SMS

### ISSUE THREAD

**Issue by maciak** [qklabs/qksms#486]
As in topic. Could you please try to add forward option on holding the message for example?

**Comment by moezbhatti** [comment]
Sorry for the late response - you can simply long-press on a message to access the Forward option

**Comment by maciak** [comment]
Hi,
Yes you are right but there is a problem as I've noticed thet it just does not work on some messages. I did not know that at first so that's why I've opened this issue. Still it does not work on some massages. I just long-press and on some it pops up with menu and on some nothing happens.
