### ISSUE TITLE
Enhancement Request: Add Name Of Sender To Group Messages

### ISSUE THREAD

**Issue by jdscren2012** [qklabs/qksms#52]
One thing that's been bugging me is that in a group message, the only way to tell who sent a message is by looking at the contact picture. I have my contact pictures synced with Facebook, so they change on a regular basis, and I can't always tell who sent a particular message. It would be nice if the sender's name was included in the message, either at the beginning, or as a signature at the end. 

Loving the app!! I love that the dev is so involved in the community and always working to improve the app.

**Comment by srcreigh** [comment]
This is absolutely a needed feature. Thanks @jdscren2012! Stay tuned.
