### ISSUE TITLE
QK reply popup does not appear after last update

### ISSUE THREAD

**Issue by reppad** [qklabs/qksms#528]
### DESCRIPTION
QK reply popup is not appear when I click on the button "REPONDRE" (I am french) on the notification
This issue appeared after last update.

### STEPS
1. receive an SMS (or mark a conversation unread)
2. expand the notification
3. click on "REPONDRE" (reply)
4. nothing append

### EXPECTED
After step 3, the QK reply popup should be displayed

### OBSERVATIONS
This feature worked before update.
I use a Galaxy S7 (European version with Exynos SOC), with stock Marshmallow firmware.
I tried to wipe app data and cache.
The button "LU" (mark as read) in the notification is working.

Apart from this detail, the application is really great ! Thanks for that !

**Comment by sm4rk0** [comment]
Works fine for me. Motorola Moto X, Lollipop 5.1, QKSMS v2.6.2

**Comment by moezbhatti** [comment]
Figured out why this is happening, should be only on android M devices
Will fix in the next update
