### ISSUE TITLE
QK Compose notification icon looks bad on light gray background

### ISSUE THREAD

**Issue by stuman421** [qklabs/qksms#55]
On lollipop the icon looks really ugly.

**Comment by stuman421** [comment]
http://imgur.com/XuPAE2E 
Ew.

**Comment by anubiann00b** [comment]
What's your device resolution?

**Comment by moezbhatti** [comment]
You're right, it shouldn't be white

**Comment by moezbhatti** [comment]
The white looks pretty bad

**Comment by Samcfuchs** [comment]
I don't know if this is a bug, just bad design. /r/CrappyDesign, in fact.

**Comment by Samcfuchs** [comment]
Actually, I'd also recommend replacing the pencil with the qk logo, just to make it special.

**Comment by moezbhatti** [comment]
Fixed in https://github.com/qklabs/qksms/commit/306d5fcc34efadbe182d53f5abc498a5212ead93
