### ISSUE TITLE
Sliding Panel Tab stuck to newest conversation

### ISSUE THREAD

**Issue by xLegoz** [qklabs/qksms#56]
While bringing back QKSMS via. a notification to the latest conversation then attempting to change to the second latest conversation I had a weird bug where the messages and contact picture did not change but the name did. This persisted until I killed the app then started it again. I haven't been able to reproduce it. I will follow up if I do manage to produce it again...

Nexus 4 Android 4.4.4 (custom rom - Paranoid Android)
Also much love <3

**Comment by srcreigh** [comment]
Thanks for the report. We'll be trying to get a repro to fix it.

**Comment by moezbhatti** [comment]
Pretty sure this was fixed a while ago, haven't seen any reports about it in quite some time

**Comment by xLegoz** [comment]
Who are you @xLegoz?!

**Comment by srcreigh** [comment]
Great question. We'll be looking into it, stay tuned for more info.
