### ISSUE TITLE
Keyboard not dismissed on sliding panel

### ISSUE THREAD

**Issue by xLegoz** [qklabs/qksms#57]
### DESCRIPTION
The keyboard does not dismiss if you make compose a new message, make a text then hit the back button to slide out the panel.

### STEPS
1) Hit compose button to create a message
2) Add a single contact (in this case it was my most recent conversation contact)
3) Message
4) Hit the back button (sliding across does not reproduce this bug)

### EXPECTED
Keyboard is dismissed.

### REALITY
Keyboard is not dismissed. Reality is harsh :(

---
I would guess the onBackButton is which is hacked in when changing from the "create a new conversation" to "existing convo" view just doesn't get the keyboard dismiss :P

Nexus 4 Android 4.4.4 (custom rom - Paranoid Android)
Much more <3

**Comment by srcreigh** [comment]
Thanks for the report, just reprod now. Will fix.

**Comment by Samcfuchs** [comment]
@srcreigh shouldn't this be closed?
