### ISSUE TITLE
Changing night mode start/end times causes some text's color to become mixed up.

### ISSUE THREAD

**Issue by starleaf1** [qklabs/qksms#58]

**Comment by srcreigh** [comment]
Thanks starleaf! More info would be great. I'll try and find some repro steps right now.

**Comment by srcreigh** [comment]
Yeah, I can't figure out what's wrong.

Can you provide some steps? See the instructions at the bottom [here](https://github.com/qklabs/qksms-tracker)

**Comment by starleaf1** [comment]
OK. I've been messing around with this settings for a while. So here are the steps to repro:
1. Open QKSMS+ settings.
2. Enable automatic night mode.
3. Change Day time begins and Night time begins settings so that the day/night mode switch is triggered.

**Comment by moezbhatti** [comment]
Does this happen every time?

**Comment by srcreigh** [comment]
Cool! Can you confirm these things?

1) What version of QKSMS you're using
2) What text is the wrong color after the night mode switch occurs

**Comment by starleaf1** [comment]
OK. I'm using v1.7.1 (May 20, 2015).
The mix-up is quite unpredictable. Sometimes it's white text on white bubble, sometimes it's dark background on day mode, sometimes it's black text on the other person's bubble, sometimes it's a combination of the above.

Also, quitting and launching the app again *always* forces the app to use day mode, no matter what time of day.

**Comment by moezbhatti** [comment]
The new bug has already been fixed, we'll be pushing it tomorrow night :)

**Comment by starleaf1** [comment]
The original bug I described above still persists in v1.8.1
Restarting the app seems to fix it until the next day/night mode switch.

**Comment by Blupi** [comment]
I confirm the bug on v2.0.1.
I had white texts on white bubbles today when it switched to night mode. Only the bubbles of my interlocutor was unreadable, mine were white text on blue bubbles (my theme color).
I checked my settings : color received messages is unckecked, color sent messages is checked. It makes sense.
