### ISSUE TITLE
Pressing my phone's menu button causes QKSMS for force close

### ISSUE THREAD

**Issue by anonymous-user** [qklabs/qksms#59]
I have an LG Optimus L9 running Android 4.1.2 and am affected by this bug:

https://code.google.com/p/android/issues/detail?id=78154

**Comment by srcreigh** [comment]
Wow this is great. I can implement that fix and setup a debug build for you.

**Comment by srcreigh** [comment]
(The debug build will be so you can verify that it solves the issue)

**Comment by anonymous-user** [comment]
Where will I be able to grab the debug build from once it is ready?

**Comment by moezbhatti** [comment]
We'll post a download link on this issue
