### ISSUE TITLE
Status Bar Color

### ISSUE THREAD

**Issue by mehrabrym** [qklabs/qksms#61]
Status bar color is a gradient, instead of flat colors. It's using kitkat way of using gradient on status bars. I'm using Android 5.0.2 on Galaxy S6.

**Comment by srcreigh** [comment]
@moezbhatti is the master of the status bar stuff.

Any ideas?

**Comment by moezbhatti** [comment]
I think it has to do with how we do our theming, vs. the conventional android way.

Can you reset app data and post a screenshot of the welcome screen? That might give me an idea of what's wrong
