### ISSUE TITLE
Call button in conversation calls 6855

### ISSUE THREAD

**Issue by srcreigh** [qklabs/qksms#63]
### DESCRIPTION
Pressing the call button in a conversation always dials 6855 rather than the contact number.

### STEPS
1. Open QKSMS.
2. Navigate to a conversation.
3. Press the call button.

### EXPECTED
The dialer is opened with the contacts phone number.

### REALITY
The dialer is opened and dials "6855"

### DEVICES
**Model**: LG Optimus G
**Carrier**: Sprint

**Comment by Samcfuchs** [comment]
I followed the steps and was unable to reproduce. Have you tested different convos and numbers?

**Comment by moezbhatti** [comment]
Bug was from a few months ago, probably safe to assume it's been fixed

**Comment by Gorneman** [comment]
Hi, bug is not fixed. I have the same problem. 
device: OnePlus X onyx E1003  OxygenOs 2.2.1
