### ISSUE TITLE
Personal LED light setting automatically resets

### ISSUE THREAD

**Issue by Marpheux** [qklabs/qksms#78]
When trying to set a personal LED for people in my notification list I noticed a bug that meant it reset to the Original LED colour for the app and would not save. 

Example of how to test

1. Set general LED colour for the app (example blue) 
2. Long hold on a conversation to bring up personal settings and then change that notification LED
3. Back out of this conversation so you're back to the default messaging inbox screen
4. Repeat step 2 and you can see that the initial colour of the LED is the default of the app

I don't know whether this is an app wide issue or simply a problem related to my phone (Samsung galaxy S5 running 5.0).

**Comment by moezbhatti** [comment]
Should have been fixed a couple months ago - closing issue
