### ISSUE TITLE
Tapping the "read" button doesn't dismiss the quick-reply panel.

### ISSUE THREAD

**Issue by starleaf1** [qklabs/qksms#80]
Also, tapping on the notification to view the message in the app causes the panel to show up on top of the app, which is redundant.

**Comment by l3d00m** [comment]
Cannot repro both. Is the problem still existing @starleaf1 ?

**Comment by moezbhatti** [comment]
I believe this only happens when the screen is off. Is that correct?

**Comment by l3d00m** [comment]
That's a problem I'm having too. (But there's another issue for that I think)

**Comment by starleaf1** [comment]
@moezbhatti Yes. This is correct. Not strictly screen off, but on lockscreen.
