### ISSUE TITLE
Things randomly disappear

### ISSUE THREAD

**Issue by lobuzz311** [qklabs/qksms#83]
Elements will randomly disappear.
- The whole chat thread will be blank all of a sudden
- The images from MMSs that have been sent / received don't show up, but the text is still there
- In the pop-up box, the message is empty, but shows the buttons to respond

In either case, I have to close out of the app & return to get the items to show up

**Comment by Pau1ey** [comment]
Having the exact same issue with disappearing pictures in conversation threads on my AT&T Samsung Galaxy Note 4 with stock unrooted Android 5.01. Sometimes even leaving the app and reopening it doesn't fit it either. If I open Textra or the stock app the pictures are there. Tried also having QKSMS as only installed messaging app with stock disabled and it still has this issue.

**Comment by ziem** [comment]
I also have similar issue.

Motorola Moto E 4G XT152, Android 5.0.2, qksms 2.2.2
![Bug](http://i.imgur.com/AM6M5GE.png)

**Comment by moezbhatti** [comment]
This might be fixed with version 2.2.4

**Comment by Samcfuchs** [comment]
@moezbhatti it is not. I have had this same issue for a while but I couldn't figure out how to repro for you guys.
