### ISSUE TITLE
Enhancement request: Implement blocker function

### ISSUE THREAD

**Issue by bleketux** [qklabs/qksms#84]
It would be great if you can implement a sms blocker function : block by keyword, block by number.
Block by keyword is filtering unknown incoming sms by a list of keyword defined by a user.
Block by number is filtering incoming sms by a list of phone number defined by a user.
Thank you.

**Comment by moezbhatti** [comment]
Block by number implemented in #209

**Comment by bleketux** [comment]
Great...
next would be : block by keyword :P

**Comment by moezbhatti** [comment]
Want to make a new issue for that and then I can close this one?

**Comment by bleketux** [comment]
Okay, I will make a new issue for that...

**Comment by l3d00m** [comment]
Can be closed @moezbhatti
