### ISSUE TITLE
QK Reply should not show in active message window

### ISSUE THREAD

**Issue by gmerrall** [qklabs/qksms#86]
v1.10.4 on Nexus 6. Also occurs on N5

The QK Reply feature is fantastic but it should be disabled if qksms is the currently active application. There's no need to popup an alert for an app you're already using.

One idea could be to add an additional option to disable QK Reply if the phone is unlocked or potentially "idle" assuming you can define what idle actually means

**Comment by moezbhatti** [comment]
#91
