### ISSUE TITLE
Significant lag/stutter when opening a conversation

### ISSUE THREAD

**Issue by TheRoboteer** [qklabs/qksms#89]
Title says it all really. Whenever I open a conversation in QKSMS there is a large stutter in the animation as the conversation slides in. It's not the fault of my phone as it is the 4GB RAM variant of the Zenfone 2

**Comment by moezbhatti** [comment]
Is this happening 100% of the time?

Does it happen with particular conversations? I can't reproduce this on my Nexus 5

**Comment by astrohm** [comment]
I've noticed this too. It occurs 100% of the time on my 2013 moto x. It seems as though other apps wait to load the conversation until the window has fully transitioned, whereas QKsms is doing both simultaneously?

**Comment by moezbhatti** [comment]
It tries to wait, but the timing is a bit off. I think I have an idea how to fix it

**Comment by Samcfuchs** [comment]
I have the same problem, view slides over into the conversation, but there's a delay before messages appear. 2013 Moto X.

**Comment by sm4rk0** [comment]
Moto X 2013 here, too, but no significant lag. It's ~1s at most. I have 10k+ messages. The lag is the same as for original Android Messaging app. I suppose it's related to database access performance. Also, QKSMS scrolls through a conversation with no stutter, while original app has some hiccups.
