### ISSUE TITLE
Can't share to a phone number only

### ISSUE THREAD

**Issue by fcastilloec** [qklabs/qksms#90]
When trying to share content from an app through QKSMS, a toast appears letting me choose from my favorite contacts or letting me type a contact's name or number, but I can't just type a new number that hasn't been saved as a contact previously. Any attempt doesn't even show the number I'm typing and it's completely impossible to share anything to somebody not in your contacts. 
It's a very annoying bug...

**Comment by l3d00m** [comment]
It is possible to share to a phone number that's not in the contacts for me. You just have to click somewhere to dismiss the suggestions.  
The color of the number (and the hint) is white and therefore invisible though, but only at the first share (after stopping the app). If you share to the app a second time shortly after the first time, the number and the hint gets shown correctly.  
LG G2 5.0.2

**Comment by fcastilloec** [comment]
@moezbhatti I don't know why this bug was closed but this issue is still very present. When I sharing something, the window shows favorite contacts and it let's me type a number/name from my address book but a new number doesn't work. I get a toast asking me to select a contact even though there's a number typed on the field. This number is no longer invisible,that's some progress but still can't share
