### ISSUE TITLE
Quick reply panel showing when it shouldn't

### ISSUE THREAD

**Issue by ahattat** [qklabs/qksms#91]
When I dismiss a notification from the lock screen, next time I unlock the phone I get an empty quick-reply panel (no contact, no message).

It shouldn't show the panel at all in my humble opinion, but if it does it should'nt be empty ;-)

**Comment by Samcfuchs** [comment]
I'm not seeing this same behavior. Needs reproduction.

**Comment by moezbhatti** [comment]
To repro it, you need to receive the message while the screen is off

**Comment by SargeKhan** [comment]
this problem also occurs when you receive message from the person who's conversation activity is open.

**Comment by moezbhatti** [comment]
Fixed in 58eaabb
