### ISSUE TITLE
Asks for In-App Purchase permission

### ISSUE THREAD

**Issue by 2016rshah** [qklabs/qksms#93]
I just downloaded the app from the Play Store (can't wait to use it) but I noticed that it asked for an in-app purchase permission. In the description there are bullets for "**No Ads**" and "**Completely Free**" so I'm assuming the app won't ever really need that permission.

**Comment by moezbhatti** [comment]
In-app payments are still in the app for people who would like to donate

It seems a bit misleading unfortunately, but there isn't really a way around it

**Comment by 2016rshah** [comment]
Okay, that makes sense (y)
