### ISSUE TITLE
Address and phone number support

### ISSUE THREAD

**Issue by sasnfbi1234** [qklabs/qksms#97]
being able to auto detect and underline for tapping addresses and phone numbers would be amazing

**Comment by moezbhatti** [comment]
Do you mean within messages?

**Comment by sasnfbi1234** [comment]
yes

**Comment by Samcfuchs** [comment]
Seconded. This is very useful in other apps.

**Comment by l3d00m** [comment]
https://github.com/googlei18n/libphonenumber/

**Comment by homersimpsons** [comment]
+1
