### ISSUE TITLE
Parse phone numbers within text and show contact

### ISSUE THREAD

**Issue by moezbhatti** [qklabs/qksms#99]
https://www.reddit.com/r/Android/comments/3h7kqr/dev_qksms_is_now_completely_free_and_open_source/cu56ebz?context=3

**Comment by ahattat** [comment]
Want this too !

**Comment by Samcfuchs** [comment]
Seconded

**Comment by sm4rk0** [comment]
Isn't this done?

**Comment by moezbhatti** [comment]
@sm4rk0 you're right, thanks for noticing! Closing the issue
